{% set name = "bmi-tester" %}
{% set version = "0.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/csdms/bmi-tester/archive/v{{ version }}.tar.gz
  sha256: 2bd32dc2c7f005af848df7a3fd230a565bafc17576c55cb3fe8d7c505789fdf2
  fn: {{ name }}-{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools
    - numpydoc
    - nose
    - numpy
    - cfunits-python
    - standard_names
    - pytest

  run:
    - python
    - setuptools
    - numpydoc
    - nose
    - numpy
    - cfunits-python
    - standard_names
    - pytest

build:
  number: 0
  entry_points:
    - bmi-test=bmi_tester.bmipytest:main
  script: python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - bmi_tester
  commands:
    - bmi-test -h

about:
  home: https://github.com/csdms/bmi-tester
  license: MIT
  license_file: LICENSE
  summary: Test a Python BMI implementation
  dev_url: https://github.com/csdms/bmi-tester
