{% set name = "bmi-tester" %}
{% set version = "0.2.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/csdms/bmi-tester/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: 63ad43e89d96db72ec0c5a489a481835126dc4bad3701d3899cfd300e27df33e

requirements:
  build:
    - python
    - setuptools
    - numpydoc
    - numpy
    - cfunits-python
    - standard_names
    - pytest

  run:
    - python
    - setuptools
    - numpydoc
    - numpy
    - cfunits-python
    - standard_names
    - pytest

build:
  number: 0
  entry_points:
    - bmi-test=bmi_tester.bmipytest:main
  script: python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - bmi_tester
  commands:
    - bmi-test -h

about:
  home: https://github.com/csdms/bmi-tester
  license: MIT
  license_file: LICENSE
  summary: Test a Python BMI implementation
  dev_url: https://github.com/csdms/bmi-tester
