{% set name = "bmi-tester" %}
{% set version = "0.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/bmi-tester
  git_tag: v{{ version }}

requirements:
  build:
    - python
    - setuptools
    - numpydoc
    - nose
    - numpy
    - cfunits-python
    - standard_names
    - pytest

  run:
    - python
    - setuptools
    - numpydoc
    - nose
    - numpy
    - cfunits-python
    - standard_names
    - pytest

build:
  number: 0
  entry_points:
    - bmi-tester = bmi_tester.cmd:main
    - bmi-test = bmi_tester.bmipytest:main
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - bmi_tester
  commands:
    - bmi-tester -h
    - bmi-nose -h


about:
  home: https://github.com/csdms/bmi-tester
  license: MIT
  license_file: LICENSE
  summary: Test a Python BMI implementation
  dev_url: https://github.com/csdms/bmi-tester
