language: generic
os:
- linux
- osx
env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
  - TRAVIS_PYTHON_VERSION="3.5"
  - TRAVIS_PYTHON_VERSION="3.6"
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
  - secure: G11Z1RNE+w74Qr99tYDYgYGTbLW2VspEQsNtj7hTubpnBZE9Tl7eBhiyDgEMEeu9byDgcH8Luyifi/LLgYzARNW0RwwJfqP8RqhuJqKJb9yz0kNf7Gfe28KGEfyUgOQK3tNUwq/T+YGD7YdBWbj/7yj6rCSAnWwK5HaNDuhcbbfGW/bC1VVxtJpPnPJ7wEhdqX0D20BuWqjGh/UQGbiNur84djpjyikLXP/fYy8uLV/1aiaV1U5C45102NYAygDIPqC4T/uCIMPotFO0IwB2WKdV5OdqdhbNDT1aLfKsHJzb5S0qJVz9Ij284CYpighlyBZ6VWGFaRdc78O3DCnl1sywI3bf/MnKf5HmISVQENPozFmICNccAGNs9BVjx0Ccyo99YhXQ6ZT2MH1FQOuddecBDdLOHvi5Hf3zBUNeqehqUyeDJ/HDRxrdxpIdwljWE8MBC13NWv+3ELyz9DtIdnm5Pu0nlwbUAuRnPKAPC8wenOAByHVQkf5HEqhVNhnF2RWyFp8JxY9yBq6Lri9iBdRM7GmDymMCFdbbe3qttuHeHOu7nD+jt3nzjQaE8f3lzLFkox7asMrE5nRa0ecPIsIy/c0BrdoONafVwsc+0x88X6B341Pl400XlB7qh0hm1VPJRNMkT3iA6GA2JxUxLzfI7KU1E2trBrPBdg0ym5Y=
sudo: false
filter_secrets: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
